// 問題リスト
// 1〜50までの問題リスト（静的）
const problems = [
    { no: 1, text: "1" },
    { no: 2, text: "2" },
    { no: 3, text: "3" },
    { no: 4, text: "4" },
    { no: 5, text: "5" },
    { no: 6, text: "6" },
    { no: 7, text: "7" },
    { no: 8, text: "8" },
    { no: 9, text: "9" },
    { no: 10, text: "10" },
    { no: 11, text: "11" },
    { no: 12, text: "12" },
    { no: 13, text: "13" },
    { no: 14, text: "14" },
    { no: 15, text: "15" },
    { no: 16, text: "16" },
    { no: 17, text: "17" },
    { no: 18, text: "18" },
    { no: 19, text: "19" },
    { no: 20, text: "20" },
    { no: 21, text: "21" },
    { no: 22, text: "22" },
    { no: 23, text: "23" },
    { no: 24, text: "24" },
    { no: 25, text: "25" },
    { no: 26, text: "26" },
    { no: 27, text: "27" },
    { no: 28, text: "28" },
    { no: 29, text: "29" },
    { no: 30, text: "30" },
    { no: 31, text: "31" },
    { no: 32, text: "32" },
    { no: 33, text: "33" },
    { no: 34, text: "34" },
    { no: 35, text: "35" },
    { no: 36, text: "36" },
    { no: 37, text: "37" },
    { no: 38, text: "38" },
    { no: 39, text: "39" },
    { no: 40, text: "40" },
    { no: 41, text: "41" },
    { no: 42, text: "42" },
    { no: 43, text: "43" },
    { no: 44, text: "44" },
    { no: 45, text: "45" },
    { no: 46, text: "46" },
    { no: 47, text: "47" },
    { no: 48, text: "48" },
    { no: 49, text: "49" },
    { no: 50, text: "50" },
  ];
  
  // 問題ごとのリンク（静的、3〜50はプレースホルダ）
  const resourcesByProblem = {
    1: {
      example: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
      drill:   "https://www.youtube.com/watch?v=ysz5S6PUM-U",
      reviewPdf:"https://drive.google.com/drive/folders/XXXXXXXXXXXX",
      review:  "https://www.youtube.com/watch?v=jNQXAC9IVRw",
    },
    2: {
      example: "https://www.youtube.com/watch?v=ScMzIvxBSi4",
      drill:   "https://www.youtube.com/watch?v=oHg5SJYRHA0",
      reviewPdf:"https://drive.google.com/drive/folders/YYYYYYYYYYYY",
      review:  "https://www.youtube.com/watch?v=V-_O7nl0Ii0",
    },
    3: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_3",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_3",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_3",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_3",
    },
    4: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_4",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_4",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_4",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_4",
    },
    5: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_5",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_5",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_5",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_5",
    },
    6: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_6",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_6",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_6",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_6",
    },
    7: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_7",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_7",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_7",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_7",
    },
    8: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_8",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_8",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_8",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_8",
    },
    9: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_9",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_9",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_9",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_9",
    },
    10: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_10",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_10",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_10",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_10",
    },
    11: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_11",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_11",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_11",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_11",
    },
    12: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_12",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_12",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_12",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_12",
    },
    13: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_13",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_13",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_13",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_13",
    },
    14: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_14",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_14",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_14",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_14",
    },
    15: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_15",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_15",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_15",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_15",
    },
    16: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_16",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_16",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_16",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_16",
    },
    17: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_17",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_17",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_17",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_17",
    },
    18: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_18",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_18",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_18",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_18",
    },
    19: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_19",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_19",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_19",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_19",
    },
    20: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_20",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_20",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_20",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_20",
    },
    21: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_21",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_21",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_21",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_21",
    },
    22: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_22",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_22",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_22",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_22",
    },
    23: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_23",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_23",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_23",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_23",
    },
    24: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_24",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_24",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_24",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_24",
    },
    25: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_25",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_25",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_25",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_25",
    },
    26: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_26",
      drill:   "https://www.youtube.com/watch?v=rqsO0U394Lc",
      reviewPdf:"https://drive.google.com/file/d/1qcVdlp2Hm_1HmCy00zXcs7JDwHXR9g5X/view?usp=sharing",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_26",
    },
    27: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_27",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_27",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_27",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_27",
    },
    28: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_28",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_28",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_28",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_28",
    },
    29: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_29",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_29",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_29",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_29",
    },
    30: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_30",
      drill:   "https://youtu.be/M69pCQq0hKQ",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_30",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_30",
    },
    31: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_31",
      drill:   "https://youtu.be/NbLllZ2iOUE",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_31",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_31",
    },
    32: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_32",
      drill:   "https://www.youtube.com/watch?v=-VXx2A20uBs",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_32",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_32",
    },
    33: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_33",
      drill:   "https://youtu.be/yW1a-MVbEg0",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_33",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_33",
    },
    34: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_34",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_34",
      reviewPdf:"https://drive.google.com/file/d/1rNVh2zSb0OkocHQ_xGEzZSs2ol8lSd7C/view?usp=sharing",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_34",
    },
    35: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_35",
      drill:   "https://www.youtube.com/watch?v=n-ZQB_sH7L8&t=351s",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_35",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_35",
    },
    36: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_36",
      drill:   "https://youtu.be/ClhfbNyAzuo",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_36",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_36",
    },
    37: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_37",
      drill:   "https://youtu.be/TUXmN1zGijs",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_37",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_37",
    },
    38: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_38",
      drill:   "https://youtu.be/wqnZZNusBT8",
      reviewPdf:"https://drive.google.com/file/d/1VRATXM8-G4ZECgUrb4mBCoLo2KwBy7Uh/view?usp=share_link",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_38",
    },
    39: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_39",
      drill:   "https://youtu.be/Tsn8z1ZL2ds",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_39",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_39",
    },
    40: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_40",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_40",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_40",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_40",
    },
    41: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_41",
      drill:   "https://youtu.be/Nu9cob7UiHA",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_41",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_41",
    },
    42: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_42",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_42",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_42",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_42",
    },
    43: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_43",
      drill:   "https://youtu.be/wqnZZNusBT8",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_43",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_43",
    },
    44: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_44",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_44",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_44",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_44",
    },
    45: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_45",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_45",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_45",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_45",
    },
    46: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_46",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_46",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_46",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_46",
    },
    47: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_47",
      drill:   "https://youtu.be/1EqUtd0NUJU",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_47",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_47",
    },
    48: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_48",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_48",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_48",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_48",
    },
    49: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_49",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_49",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_49",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_49",
    },
    50: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_50",
      drill:   "https://youtu.be/Zt8hj8syr94",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_50",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_50",
    },
  };

  export { problems, resourcesByProblem };