// 問題リスト
// 1〜50までの問題リスト（静的）
const problems = [
    { no: 1, text: "1" },
    { no: 2, text: "2" },
    { no: 3, text: "3" },
    { no: 4, text: "4" },
    { no: 5, text: "5" },
    { no: 6, text: "6" },
    { no: 7, text: "7" },
    { no: 8, text: "8" },
    { no: 9, text: "9" },
    { no: 10, text: "10" },
    { no: 11, text: "11" },
    { no: 12, text: "12" },
    { no: 13, text: "13" },
    { no: 14, text: "14" },
    { no: 15, text: "15" },
    { no: 16, text: "16" },
    { no: 17, text: "17" },
    { no: 18, text: "18" },
    { no: 19, text: "19" },
    { no: 20, text: "20" },
    { no: 21, text: "21" },
    { no: 22, text: "22" },
    { no: 23, text: "23" },
    { no: 24, text: "24" },
    { no: 25, text: "25" },
    { no: 26, text: "26" },
    { no: 27, text: "27" },
    { no: 28, text: "28" },
    { no: 29, text: "29" },
    { no: 30, text: "30" },
    { no: 31, text: "31" },
    { no: 32, text: "32" },
    { no: 33, text: "33" },
    { no: 34, text: "34" },
    { no: 35, text: "35" },
    { no: 36, text: "36" },
    { no: 37, text: "37" },
    { no: 38, text: "38" },
    { no: 39, text: "39" },
    { no: 40, text: "40" },
    { no: 41, text: "41" },
    { no: 42, text: "42" },
    { no: 43, text: "43" },
    { no: 44, text: "44" },
    { no: 45, text: "45" },
    { no: 46, text: "46" },
    { no: 47, text: "47" },
    { no: 48, text: "48" },
    { no: 49, text: "49" },
    { no: 50, text: "50" },
    { no: 51, text: "51" },
    { no: 52, text: "52" },
    { no: 53, text: "53" },
    { no: 54, text: "54" },
    { no: 55, text: "55" },
    { no: 56, text: "56" },
    { no: 57, text: "57" },
    { no: 58, text: "58" },
    { no: 59, text: "59" },
    { no: 60, text: "60" },
    { no: 61, text: "61" },
    { no: 62, text: "62" },
    { no: 63, text: "63" },
    { no: 64, text: "64" },
    { no: 65, text: "65" },
    { no: 66, text: "66" },
    { no: 67, text: "67" },
    { no: 68, text: "68" },
    { no: 69, text: "69" },
    { no: 70, text: "70" },
    { no: 71, text: "71" },
    { no: 72, text: "72" },
    { no: 73, text: "73" },
    { no: 74, text: "74" },
    { no: 75, text: "75" },
    { no: 76, text: "76" },
    { no: 77, text: "77" },
    { no: 78, text: "78" },
    { no: 79, text: "79" },
    { no: 80, text: "80" },
    { no: 81, text: "81" },
    { no: 82, text: "82" },
    { no: 83, text: "83" },
    { no: 84, text: "84" },
    { no: 85, text: "85" },
    { no: 86, text: "86" },
    { no: 87, text: "87" },
    { no: 88, text: "88" },
    { no: 89, text: "89" },
    { no: 90, text: "90" },
    { no: 91, text: "91" },
    { no: 92, text: "92" },
    { no: 93, text: "93" },
    { no: 94, text: "94" },
    { no: 95, text: "95" },
    { no: 96, text: "96" },
    { no: 97, text: "97" },
    { no: 98, text: "98" },
    { no: 99, text: "99" },
    { no: 100, text: "100" },
    { no: 101, text: "101" },
    { no: 102, text: "102" },
    { no: 103, text: "103" },
    { no: 104, text: "104" },
    { no: 105, text: "105" },
    { no: 106, text: "106" },
    { no: 107, text: "107" },
    { no: 108, text: "108" },
    { no: 109, text: "109" },
    { no: 110, text: "110" },
    { no: 111, text: "111" },
    { no: 112, text: "112" },
    { no: 113, text: "113" },
    { no: 114, text: "114" },
    { no: 115, text: "115" },
    { no: 116, text: "116" },
    { no: 117, text: "117" },
    { no: 118, text: "118" },
    { no: 119, text: "119" },
    { no: 120, text: "120" },
    { no: 121, text: "121" },
    { no: 122, text: "122" },
    { no: 123, text: "123" },
    { no: 124, text: "124" },
    { no: 125, text: "125" },
    { no: 126, text: "126" },
    { no: 127, text: "127" },
    { no: 128, text: "128" },
    { no: 129, text: "129" },
    { no: 130, text: "130" },
    { no: 131, text: "131" },
    { no: 132, text: "132" },
    { no: 133, text: "133" },
    { no: 134, text: "134" },
    { no: 135, text: "135" },
    { no: 136, text: "136" },
    { no: 137, text: "137" },
    { no: 138, text: "138" },
    { no: 139, text: "139" },
    { no: 140, text: "140" },
    { no: 141, text: "141" },
    { no: 142, text: "142" },
    { no: 143, text: "143" },
    { no: 144, text: "144" },
    { no: 145, text: "145" },
    { no: 146, text: "146" },
    { no: 147, text: "147" },
    { no: 148, text: "148" },
    { no: 149, text: "149" },
    { no: 150, text: "150" },
  ];
  
  // 問題ごとのリンク（静的、3〜50はプレースホルダ）
  const resourcesByProblem = {
    1: {
      example: "https://www.youtube.com/watch?v=1_4AR-nPpwA",
      drill:   "https://www.youtube.com/watch?v=1_4AR-nPpwA",
      reviewPdf:"https://drive.google.com/drive/folders/XXXXXXXXXXXX",
      review:  "https://www.youtube.com/watch?v=jNQXAC9IVRw",
    },
    2: {
      example: "https://www.youtube.com/watch?v=1_4AR-nPpwA",
      drill:   "https://www.youtube.com/watch?v=1_4AR-nPpwA",
      reviewPdf:"https://drive.google.com/drive/folders/YYYYYYYYYYYY",
      review:  "https://www.youtube.com/watch?v=V-_O7nl0Ii0",
    },
    3: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_3",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_3",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_3",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_3",
    },
    4: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_4",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_4",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_4",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_4",
    },
    5: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_5",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_5",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_5",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_5",
    },
    6: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_6",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_6",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_6",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_6",
    },
    7: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_7",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_7",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_7",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_7",
    },
    8: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_8",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_8",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_8",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_8",
    },
    9: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_9",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_9",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_9",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_9",
    },
    10: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_10",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_10",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_10",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_10",
    },
    11: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_11",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_11",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_11",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_11",
    },
    12: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_12",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_12",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_12",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_12",
    },
    13: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_13",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_13",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_13",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_13",
    },
    14: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_14",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_14",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_14",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_14",
    },
    15: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_15",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_15",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_15",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_15",
    },
    16: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_16",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_16",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_16",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_16",
    },
    17: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_17",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_17",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_17",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_17",
    },
    18: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_18",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_18",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_18",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_18",
    },
    19: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_19",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_19",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_19",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_19",
    },
    20: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_20",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_20",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_20",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_20",
    },
    21: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_21",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_21",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_21",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_21",
    },
    22: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_22",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_22",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_22",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_22",
    },
    23: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_23",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_23",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_23",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_23",
    },
    24: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_24",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_24",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_24",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_24",
    },
    25: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_25",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_25",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_25",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_25",
    },
    26: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_26",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_26",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_26",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_26",
    },
    27: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_27",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_27",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_27",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_27",
    },
    28: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_28",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_28",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_28",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_28",
    },
    29: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_29",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_29",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_29",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_29",
    },
    30: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_30",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_30",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_30",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_30",
    },
    31: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_31",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_31",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_31",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_31",
    },
    32: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_32",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_32",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_32",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_32",
    },
    33: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_33",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_33",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_33",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_33",
    },
    34: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_34",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_34",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_34",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_34",
    },
    35: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_35",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_35",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_35",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_35",
    },
    36: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_36",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_36",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_36",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_36",
    },
    37: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_37",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_37",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_37",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_37",
    },
    38: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_38",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_38",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_38",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_38",
    },
    39: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_39",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_39",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_39",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_39",
    },
    40: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_40",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_40",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_40",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_40",
    },
    41: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_41",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_41",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_41",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_41",
    },
    42: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_42",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_42",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_42",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_42",
    },
    43: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_43",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_43",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_43",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_43",
    },
    44: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_44",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_44",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_44",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_44",
    },
    45: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_45",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_45",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_45",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_45",
    },
    46: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_46",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_46",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_46",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_46",
    },
    47: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_47",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_47",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_47",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_47",
    },
    48: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_48",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_48",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_48",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_48",
    },
    49: {
      example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_49",
      drill:   "https://www.youtube.com/watch?v=REPLACE_DRILL_49",
      reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_49",
      review:  "https://www.youtube.com/watch?v=REPLACE_REVIEW_49",
    },
    50: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_50", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_50", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_50", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_50", },
    51: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_51", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_51", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_51", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_51", },
    52: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_52", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_52", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_52", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_52", },
    53: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_53", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_53", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_53", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_53", },
    54: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_54", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_54", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_54", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_54", },
    55: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_55", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_55", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_55", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_55", },
    56: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_56", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_56", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_56", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_56", },
    57: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_57", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_57", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_57", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_57", },
    58: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_58", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_58", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_58", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_58", },
    59: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_59", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_59", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_59", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_59", },
    60: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_60", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_60", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_60", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_60", },
    61: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_61", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_61", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_61", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_61", },
    62: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_62", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_62", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_62", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_62", },
    63: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_63", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_63", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_63", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_63", },
    64: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_64", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_64", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_64", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_64", },
    65: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_65", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_65", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_65", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_65", },
    66: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_66", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_66", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_66", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_66", },
    67: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_67", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_67", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_67", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_67", },
    68: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_68", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_68", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_68", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_68", },
    69: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_69", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_69", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_69", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_69", },
    70: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_70", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_70", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_70", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_70", },
    71: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_71", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_71", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_71", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_71", },
    72: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_72", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_72", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_72", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_72", },
    73: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_73", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_73", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_73", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_73", },
    74: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_74", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_74", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_74", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_74", },
    75: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_75", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_75", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_75", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_75", },
    76: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_76", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_76", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_76", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_76", },
    77: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_77", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_77", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_77", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_77", },
    78: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_78", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_78", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_78", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_78", },
    79: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_79", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_79", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_79", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_79", },
    80: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_80", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_80", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_80", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_80", },
    81: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_81", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_81", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_81", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_81", },
    82: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_82", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_82", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_82", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_82", },
    83: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_83", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_83", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_83", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_83", },
    84: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_84", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_84", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_84", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_84", },
    85: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_85", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_85", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_85", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_85", },
    86: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_86", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_86", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_86", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_86", },
    87: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_87", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_87", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_87", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_87", },
    88: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_88", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_88", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_88", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_88", },
    89: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_89", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_89", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_89", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_89", },
    90: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_90", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_90", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_90", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_90", },
    91: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_91", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_91", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_91", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_91", },
    92: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_92", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_92", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_92", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_92", },
    93: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_93", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_93", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_93", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_93", },
    94: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_94", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_94", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_94", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_94", },
    95: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_95", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_95", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_95", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_95", },
    96: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_96", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_96", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_96", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_96", },
    97: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_97", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_97", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_97", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_97", },
    98: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_98", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_98", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_98", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_98", },
    99: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_99", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_99", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_99", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_99", },
    100: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_100", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_100", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_100", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_100", },
    101: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_101", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_101", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_101", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_101", },
    102: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_102", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_102", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_102", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_102", },
    103: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_103", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_103", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_103", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_103", },
    104: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_104", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_104", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_104", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_104", },
    105: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_105", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_105", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_105", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_105", },
    106: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_106", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_106", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_106", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_106", },
    107: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_107", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_107", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_107", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_107", },
    108: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_108", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_108", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_108", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_108", },
    109: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_109", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_109", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_109", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_109", },
    110: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_110", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_110", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_110", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_110", },
    111: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_111", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_111", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_111", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_111", },
    112: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_112", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_112", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_112", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_112", },
    113: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_113", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_113", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_113", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_113", },
    114: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_114", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_114", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_114", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_114", },
    115: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_115", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_115", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_115", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_115", },
    116: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_116", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_116", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_116", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_116", },
    117: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_117", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_117", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_117", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_117", },
    118: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_118", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_118", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_118", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_118", },
    119: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_119", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_119", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_119", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_119", },
    120: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_120", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_120", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_120", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_120", },
    121: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_121", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_121", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_121", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_121", },
    122: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_122", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_122", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_122", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_122", },
    123: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_123", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_123", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_123", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_123", },
    124: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_124", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_124", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_124", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_124", },
    125: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_125", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_125", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_125", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_125", },
    126: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_126", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_126", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_126", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_126", },
    127: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_127", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_127", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_127", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_127", },
    128: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_128", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_128", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_128", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_128", },
    129: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_129", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_129", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_129", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_129", },
    130: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_130", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_130", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_130", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_130", },
    131: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_131", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_131", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_131", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_131", },
    132: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_132", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_132", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_132", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_132", },
    133: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_133", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_133", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_133", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_133", },
    134: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_134", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_134", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_134", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_134", },
    135: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_135", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_135", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_135", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_135", },
    136: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_136", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_136", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_136", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_136", },
    137: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_137", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_137", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_137", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_137", },
    138: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_138", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_138", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_138", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_138", },
    139: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_139", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_139", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_139", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_139", },
    140: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_140", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_140", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_140", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_140", },
    141: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_141", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_141", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_141", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_141", },
    142: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_142", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_142", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_142", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_142", },
    143: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_143", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_143", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_143", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_143", },
    144: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_144", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_144", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_144", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_144", },
    145: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_145", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_145", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_145", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_145", },
    146: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_146", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_146", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_146", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_146", },
    147: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_147", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_147", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_147", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_147", },
    148: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_148", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_148", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_148", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_148", },
    149: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_149", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_149", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_149", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_149", },
    150: { example: "https://www.youtube.com/watch?v=REPLACE_EXAMPLE_150", drill: "https://www.youtube.com/watch?v=REPLACE_DRILL_150", reviewPdf:"https://drive.google.com/drive/folders/REPLACE_PDF_150", review: "https://www.youtube.com/watch?v=REPLACE_REVIEW_150", },

      };

  export { problems, resourcesByProblem };